// Minimal ZIP extractor. Pure Node, no deps.
//
// Supports the two compression methods our pet zips ever contain:
//   - 0  (store)
//   - 8  (deflate)
//
// We deliberately do NOT support encryption, ZIP64, or multi-disk archives.
// Pet zips are server-generated by fflate, well under 100 MB, single-disk.

import { inflateRawSync } from 'node:zlib'

function readU16(buf, off) { return buf[off] | (buf[off + 1] << 8) }
function readU32(buf, off) {
  return (buf[off] | (buf[off + 1] << 8) | (buf[off + 2] << 16) | (buf[off + 3] * 0x1000000)) >>> 0
}

// End-of-central-directory record signature: 0x06054b50.
function findEocd(buf) {
  // EOCD is at most 22 bytes + 0xFFFF comment. Scan backward.
  const maxBack = Math.min(buf.length, 22 + 0xffff)
  for (let i = buf.length - 22; i >= buf.length - maxBack; i--) {
    if (readU32(buf, i) === 0x06054b50) return i
  }
  throw new Error('zip: end-of-central-directory not found')
}

export function parseZip(buf) {
  const eocd = findEocd(buf)
  const entryCount = readU16(buf, eocd + 10)
  const cdSize = readU32(buf, eocd + 12)
  const cdOffset = readU32(buf, eocd + 16)
  if (cdOffset + cdSize > buf.length) {
    throw new Error('zip: central directory bounds out of range')
  }

  const entries = []
  let p = cdOffset
  for (let i = 0; i < entryCount; i++) {
    if (readU32(buf, p) !== 0x02014b50) throw new Error(`zip: bad central directory entry #${i}`)
    const method = readU16(buf, p + 10)
    const compSize = readU32(buf, p + 20)
    const uncompSize = readU32(buf, p + 24)
    const nameLen = readU16(buf, p + 28)
    const extraLen = readU16(buf, p + 30)
    const commentLen = readU16(buf, p + 32)
    const localOff = readU32(buf, p + 42)
    const name = buf.slice(p + 46, p + 46 + nameLen).toString('utf8')

    // Local file header: skip its variable-length name + extra to find data.
    if (readU32(buf, localOff) !== 0x04034b50) throw new Error(`zip: bad local header for ${name}`)
    const lhNameLen = readU16(buf, localOff + 26)
    const lhExtraLen = readU16(buf, localOff + 28)
    const dataStart = localOff + 30 + lhNameLen + lhExtraLen
    const compBytes = buf.slice(dataStart, dataStart + compSize)

    let data
    if (method === 0) {
      data = compBytes
    } else if (method === 8) {
      data = inflateRawSync(compBytes)
      if (data.length !== uncompSize) {
        throw new Error(`zip: ${name} decompressed to ${data.length} bytes, expected ${uncompSize}`)
      }
    } else {
      throw new Error(`zip: ${name} uses unsupported compression method ${method}`)
    }

    entries.push({ name, data })
    p += 46 + nameLen + extraLen + commentLen
  }
  return entries
}
